import os
from dotenv import load_dotenv
from huggingface_hub import InferenceClient


load_dotenv()


class GemmaAnalyzer:

    def __init__(
        self,
        model_id="google/gemma-4-E2B-it"
    ):

        self.model_id = model_id

        self.client = InferenceClient(
            api_key=os.getenv("HF_TOKEN")
        )


    def create_prompt(self, data, patient_info=None):

        patient_info = patient_info or {}

        patient_name = patient_info.get(
            "patient_name",
            "Not provided"
        )

        age = patient_info.get(
            "age",
            "Not provided"
        )

        gender = patient_info.get(
            "gender",
            "Not provided"
        )

        clinical_information = patient_info.get(
            "clinical_information",
            "Not provided"
        )

        image_name = data.get(
            "image_name",
            "Not available"
        )

        nodule_detected = data.get(
            "nodule_detected",
            None
        )

        nodule_text = (
            "Yes"
            if nodule_detected is True
            else "No"
            if nodule_detected is False
            else "Not available"
        )

        detection_confidence = data.get(
            "detection_confidence"
        )

        classification = data.get(
            "classification",
            "Not available"
        )

        classification_confidence = data.get(
            "classification_confidence"
        )

        bounding_box = data.get(
            "bounding_box",
            "Not available"
        )

        detection_confidence_text = (

            f"{detection_confidence * 100:.2f}%"

            if detection_confidence is not None

            else "Not available"

        )

        classification_confidence_text = (

            f"{classification_confidence * 100:.2f}%"

            if classification_confidence is not None

            else "Not available"

        )


        prompt = f"""
    You are ThyroGuide AI, an AI-assisted thyroid ultrasound report explanation system.

    Generate a professional structured thyroid ultrasound AI-assisted report.

    IMPORTANT:

    The computer vision system has already produced the classification.

    Do NOT perform a new diagnosis.

    Do NOT change the provided classification.

    Do NOT invent ultrasound findings.

    Do NOT invent TI-RADS scores.

    Do NOT invent symptoms, biopsy results, medical history, or clinical information.

    Clearly distinguish between:

    1. AI-generated computer vision results
    2. Patient-provided information
    3. Medical limitations

    PATIENT INFORMATION:

    Patient Name: {patient_name}

    Age: {age}

    Gender: {gender}

    Clinical Information:
    {clinical_information}


    COMPUTER VISION RESULTS:

    Image Name: {image_name}

    Nodule Detected: {nodule_text}

    Detection Confidence: {detection_confidence_text}

    CNN Classification: {classification}

    Classification Confidence: {classification_confidence_text}

    Bounding Box: {bounding_box}


    GENERATE THE REPORT USING EXACTLY THESE SECTIONS:

    ULTRASOUND AI-ASSISTED ANALYSIS

    Patient Information

    Patient Name: {patient_name}

    Age: {age}

    Gender: {gender}

    Clinical Information:
    {clinical_information}


    AI DETECTION SUMMARY

    Explain whether a thyroid nodule was detected.

    If detected, state that the location is represented by the YOLO bounding box.

    Do not invent anatomical locations that were not provided.


    AI CLASSIFICATION SUMMARY

    State exactly:

    {classification}

    Explain that this is the classification produced by the CNN model.

    Do not change the classification.


    CONFIDENCE INTERPRETATION

    Explain separately:

    Detection confidence: {detection_confidence_text}

    Classification confidence: {classification_confidence_text}


    EXPLAINABILITY

    Explain that:

    - YOLO provides the detected bounding box.
    - CNN provides the classification.
    - Grad-CAM highlights image regions that contributed to the CNN decision.
    - Grad-CAM does not prove a diagnosis.


    PATIENT-FRIENDLY EXPLANATION

    Explain the AI result in simple language.

    Do not state that the AI result is a confirmed diagnosis.


    IMPORTANT LIMITATIONS

    Clearly state that:

    - This is an AI-assisted prediction.
    - It is not a definitive medical diagnosis.
    - The classification should not be interpreted as a confirmed diagnosis.
    - Professional medical evaluation is recommended.
    - Additional clinical assessment and appropriate diagnostic procedures may be required.


    REPORT FOOTER

    Report generated by ThyroGuide AI.

    Return only the report.
    """


        return prompt

    def generate_report(
        self,
        data,
        patient_info=None
    ):

        prompt = self.create_prompt(
            data,
            patient_info
        )

        response = self.client.chat_completion(

            model=self.model_id,

            messages=[

                {
                    "role": "user",

                    "content": prompt

                }

            ],

            max_tokens=1200,

            temperature=0.1

        )


        message = response.choices[0].message


        if message.content:

            return message.content


        elif message.reasoning:

            return message.reasoning


        else:

            return (
                "No report was generated."
            )